on:
  push:
    paths:
    - .github/actions/workflows/cron.yml
    - check.py
    - requirements-check.txt
  schedule:
  - cron: '*/5 * * * 2,3'

jobs:
  sync:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Synchronize between workflow runs
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  check:
    needs: sync
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-check.txt
    - name: Check JDK 8 updates
      run: ./check.py 8 https://www.oracle.com/java/technologies/javase/javase-jdk8-downloads.html
    - name: Check JDK 11 updates
      run: ./check.py 11 https://www.oracle.com/java/technologies/javase-jdk11-downloads.html
    - name: Check JDK 15 updates
      run: ./check.py 15 https://www.oracle.com/java/technologies/javase-jdk15-downloads.html
    - name: Commit if dirty
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git add --all --verbose
        if ! git diff --quiet HEAD; then
        	git config user.name 'GitHub Actions'
        	git config user.email "$(whoami)@$(hostname --fqdn)"
        	git config http.https://github.com/.extraheader "Authorization: Basic $(echo -n "dummy:${PERSONAL_ACCESS_TOKEN}" | base64 --wrap=0)"
        	git commit --quiet --message 'automatic commit'
        	git push --quiet origin master
        fi
