on: page_build

jobs:
  sync:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Synchronize between workflow runs
      uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dispatch:
    needs: sync
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        major: [8, 11, 14]
    steps:
    - name: Load metadata from gh-pages
      run: |
        eval "$(curl -fsSL https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/gh-pages/oracle-java-${{ matrix.major }}.sh)"
        echo "::set-env name=UPDATED::${UPDATED}"
    - name: Trigger downstream repository_dispatch
      if: env.UPDATED == 'true'
      env:
        REPOSITORY: zhangyoufu/oracle-jre-headless
      run: curl --silent --show-error --request POST --user "dummy:${{ secrets.PERSONAL_ACCESS_TOKEN }}" --data "$(jq --null-input --compact-output '{event_type:"build for JDK ${{ matrix.major }}",client_payload:{major:${{ matrix.major }}}}')" "https://api.github.com/repos/${REPOSITORY}/dispatches"
